In [ ]:
import pandas as pd
from models.regression.price_regression_models import (
    LinearRegressionPriceModel,
    RandomForestPriceModel,
    LightGBMPriceModel,
    XGBoostPriceModel,
    compare_regression_models,
)

df = pd.read_csv("Apart Deal.csv")

# 모델은 필요한만큼만 사용할 것(필요하지 않은 것은 지우거나 주석 처리)
models = [
    LinearRegressionPriceModel(sample_size=100_000),
    RandomForestPriceModel(sample_size=100_000),
    LightGBMPriceModel(sample_size=100_000),
    XGBoostPriceModel(sample_size=100_000),
]

result_df = compare_regression_models(models, df)
result_df.to_csv("학습결과1.csv")

C:\Users\윤승혁\AppData\Local\Temp\ipykernel_12852\121918963.py:10: DtypeWarning: Columns (6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Apart Deal.csv")
c:\miniconda\envs\test_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [9]:
result_df2 = pd.read_csv('학습결과4.csv')
result_df2

,model,MAE,MSE,RMSE,MAPE,R2,rows,train_rows,test_rows,error
0,XGBoost,3975.552331,6.084922e+07,7800.590941,14.705228,0.928772,20000,80000,20000,NaN
1,LightGBM,4020.286710,6.352421e+07,7970.207942,15.002232,0.925641,20000,80000,20000,NaN
2,RandomForest,4105.859265,8.070833e+07,8983.781303,14.202529,0.905526,20000,80000,20000,NaN
3,LinearRegression,8692.311103,2.519987e+08,15874.468232,37.972303,0.705021,20000,80000,20000,NaN

In [11]:
result_df = pd.read_csv('학습결과1.csv')
result_df

,model,MAE,MSE,RMSE,MAPE,R2,rows,train_rows,test_rows,error
0,XGBoost,5238.003731,6.970337e+07,8348.854355,21.409111,0.892846,20000,80000,20000,NaN
1,LightGBM,4853.536464,6.685003e+07,8176.186761,18.251910,0.897233,20000,80000,20000,NaN
2,RandomForest,7655.107637,1.245554e+08,11160.441176,33.940435,0.808523,20000,80000,20000,NaN
3,LinearRegression,7297.648165,1.585629e+08,12592.177537,29.570450,0.756244,20000,80000,20000,NaN

In [2]:
!pip install lightgbm xgboost

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\miniconda\envs\test_env\lib\site-packages (from lightgbm) (2.2.5)
Requirement already satisfied: scipy in c:\miniconda\envs\test_env\lib\site-packages (from lightgbm) (1.15.3)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 19.2 MB/s  0:00:00
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   -- ------------------------------------- 6.3/101.7 MB 29.7 MB/s eta 0:00:04
   ---- ----------------------------------- 10.5/101.7 MB 25.2 MB/s eta 0:00:04
   ------ --------------------------------- 17.3/101.7 MB 27.3 MB/s eta 0:00:04
   --------- ------------------------------ 25.2/101.7 MB 29.5 MB/s eta 0:00:03
   -------------- ------------------------- 35.7/101.7 MB 33.8 MB/s eta 0:00:02
   -------------- ------------------------- 35.7/101.7 MB 33.8 MB/s eta 0:00:02
   --------------- ------------------------ 39.3/101.7 MB 26.3 MB/s eta 0:00:03
   ------------------ --------------------- 47.2/101.7 MB 27.8 MB/s eta 0:00:02
   --------------------- ------------------ 55.6/101.7 MB 29.5 MB/s eta 0:00:02
   --------------------- ------------------ 55.6/101.7 MB 29.5 MB/s eta 0:00:02
   ------------------------- -------------- 64.2/101.7 MB 27.3 MB/s eta 0:00:02
   --------------------------- ------------ 70.3/101.7 MB 27.5 MB/s eta 0:00:02
   ------------------------------- -------- 80.5/101.7 MB 29.0 MB/s eta 0:00:01
   ----------------------------------- ---- 90.7/101.7 MB 30.5 MB/s eta 0:00:01
   -------------------------------------- - 97.5/101.7 MB 31.3 MB/s eta 0:00:01
   --------------------------------------  100.7/101.7 MB 30.5 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 28.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 27.2 MB/s  0:00:03
Installing collected packages: xgboost, lightgbm

   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   ---------------------------------------- 0/2 [xgboost]
   -------------------- ------------------- 1/2 [lightgbm]
   -------------------- ------------------- 1/2 [lightgbm]
   ---------------------------------------- 2/2 [lightgbm]

Successfully installed lightgbm-4.6.0 xgboost-3.2.0